// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Represents an individual task
type Todo struct {
	// Primary identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Boolean flag indicating whether or not the todo has been completed
	Complete bool `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"`
	// Completion timestamp
	CompletedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// Creation timestamp
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Optional detail
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Task title
	Title                string   `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_5a569386f6c2c688, []int{0}
}
func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (dst *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(dst, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Todo) GetComplete() bool {
	if m != nil {
		return m.Complete
	}
	return false
}

func (m *Todo) GetCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CompletedAt
	}
	return nil
}

func (m *Todo) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Todo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// Describes the input to a CreateTodo operation
type CreateTodoInput struct {
	// Optional detail
	// @inject_tag: validate:"min=3"
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Task title
	// @inject_tag: validate:"required,min=3"
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTodoInput) Reset()         { *m = CreateTodoInput{} }
func (m *CreateTodoInput) String() string { return proto.CompactTextString(m) }
func (*CreateTodoInput) ProtoMessage()    {}
func (*CreateTodoInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_5a569386f6c2c688, []int{1}
}
func (m *CreateTodoInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTodoInput.Unmarshal(m, b)
}
func (m *CreateTodoInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTodoInput.Marshal(b, m, deterministic)
}
func (dst *CreateTodoInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTodoInput.Merge(dst, src)
}
func (m *CreateTodoInput) XXX_Size() int {
	return xxx_messageInfo_CreateTodoInput.Size(m)
}
func (m *CreateTodoInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTodoInput.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTodoInput proto.InternalMessageInfo

func (m *CreateTodoInput) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateTodoInput) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// Describes the output from a successful CreateTodo operation
type CreateTodoOutput struct {
	// Newly created Todo
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTodoOutput) Reset()         { *m = CreateTodoOutput{} }
func (m *CreateTodoOutput) String() string { return proto.CompactTextString(m) }
func (*CreateTodoOutput) ProtoMessage()    {}
func (*CreateTodoOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_5a569386f6c2c688, []int{2}
}
func (m *CreateTodoOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTodoOutput.Unmarshal(m, b)
}
func (m *CreateTodoOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTodoOutput.Marshal(b, m, deterministic)
}
func (dst *CreateTodoOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTodoOutput.Merge(dst, src)
}
func (m *CreateTodoOutput) XXX_Size() int {
	return xxx_messageInfo_CreateTodoOutput.Size(m)
}
func (m *CreateTodoOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTodoOutput.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTodoOutput proto.InternalMessageInfo

func (m *CreateTodoOutput) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

// Describes the input to a ListTodos operation
type ListTodosInput struct {
	// Pagination offset
	After string `protobuf:"bytes,1,opt,name=after,proto3" json:"after,omitempty"`
	// Page size
	First                int32    `protobuf:"varint,2,opt,name=first,proto3" json:"first,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTodosInput) Reset()         { *m = ListTodosInput{} }
func (m *ListTodosInput) String() string { return proto.CompactTextString(m) }
func (*ListTodosInput) ProtoMessage()    {}
func (*ListTodosInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_5a569386f6c2c688, []int{3}
}
func (m *ListTodosInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTodosInput.Unmarshal(m, b)
}
func (m *ListTodosInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTodosInput.Marshal(b, m, deterministic)
}
func (dst *ListTodosInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTodosInput.Merge(dst, src)
}
func (m *ListTodosInput) XXX_Size() int {
	return xxx_messageInfo_ListTodosInput.Size(m)
}
func (m *ListTodosInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTodosInput.DiscardUnknown(m)
}

var xxx_messageInfo_ListTodosInput proto.InternalMessageInfo

func (m *ListTodosInput) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

func (m *ListTodosInput) GetFirst() int32 {
	if m != nil {
		return m.First
	}
	return 0
}

// Describes the output from a successful ListTodos operation
type ListTodosOutput struct {
	// List of Todos
	Todos []*Todo `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	// Total number of todos
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTodosOutput) Reset()         { *m = ListTodosOutput{} }
func (m *ListTodosOutput) String() string { return proto.CompactTextString(m) }
func (*ListTodosOutput) ProtoMessage()    {}
func (*ListTodosOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_5a569386f6c2c688, []int{4}
}
func (m *ListTodosOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTodosOutput.Unmarshal(m, b)
}
func (m *ListTodosOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTodosOutput.Marshal(b, m, deterministic)
}
func (dst *ListTodosOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTodosOutput.Merge(dst, src)
}
func (m *ListTodosOutput) XXX_Size() int {
	return xxx_messageInfo_ListTodosOutput.Size(m)
}
func (m *ListTodosOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTodosOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ListTodosOutput proto.InternalMessageInfo

func (m *ListTodosOutput) GetTodos() []*Todo {
	if m != nil {
		return m.Todos
	}
	return nil
}

func (m *ListTodosOutput) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*Todo)(nil), "mindflash.todo.Todo")
	proto.RegisterType((*CreateTodoInput)(nil), "mindflash.todo.CreateTodoInput")
	proto.RegisterType((*CreateTodoOutput)(nil), "mindflash.todo.CreateTodoOutput")
	proto.RegisterType((*ListTodosInput)(nil), "mindflash.todo.ListTodosInput")
	proto.RegisterType((*ListTodosOutput)(nil), "mindflash.todo.ListTodosOutput")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodosClient is the client API for Todos service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodosClient interface {
	// Creates a new Todo
	CreateTodo(ctx context.Context, in *CreateTodoInput, opts ...grpc.CallOption) (*CreateTodoOutput, error)
	// Retrieves a paginated list of Todos
	ListTodos(ctx context.Context, in *ListTodosInput, opts ...grpc.CallOption) (*ListTodosOutput, error)
}

type todosClient struct {
	cc *grpc.ClientConn
}

func NewTodosClient(cc *grpc.ClientConn) TodosClient {
	return &todosClient{cc}
}

func (c *todosClient) CreateTodo(ctx context.Context, in *CreateTodoInput, opts ...grpc.CallOption) (*CreateTodoOutput, error) {
	out := new(CreateTodoOutput)
	err := c.cc.Invoke(ctx, "/mindflash.todo.Todos/CreateTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todosClient) ListTodos(ctx context.Context, in *ListTodosInput, opts ...grpc.CallOption) (*ListTodosOutput, error) {
	out := new(ListTodosOutput)
	err := c.cc.Invoke(ctx, "/mindflash.todo.Todos/ListTodos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodosServer is the server API for Todos service.
type TodosServer interface {
	// Creates a new Todo
	CreateTodo(context.Context, *CreateTodoInput) (*CreateTodoOutput, error)
	// Retrieves a paginated list of Todos
	ListTodos(context.Context, *ListTodosInput) (*ListTodosOutput, error)
}

func RegisterTodosServer(s *grpc.Server, srv TodosServer) {
	s.RegisterService(&_Todos_serviceDesc, srv)
}

func _Todos_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTodoInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodosServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mindflash.todo.Todos/CreateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodosServer).CreateTodo(ctx, req.(*CreateTodoInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todos_ListTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTodosInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodosServer).ListTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mindflash.todo.Todos/ListTodos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodosServer).ListTodos(ctx, req.(*ListTodosInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Todos_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mindflash.todo.Todos",
	HandlerType: (*TodosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTodo",
			Handler:    _Todos_CreateTodo_Handler,
		},
		{
			MethodName: "ListTodos",
			Handler:    _Todos_ListTodos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_todo_5a569386f6c2c688) }

var fileDescriptor_todo_5a569386f6c2c688 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0xaa, 0xd3, 0x40,
	0x14, 0xc6, 0x99, 0xdc, 0xa6, 0xb6, 0x27, 0x92, 0xab, 0x43, 0x17, 0x21, 0x88, 0x0d, 0x59, 0x85,
	0xbb, 0x48, 0xa0, 0xae, 0x94, 0xeb, 0xe2, 0xea, 0xea, 0x82, 0x20, 0xc4, 0xae, 0x44, 0x90, 0x69,
	0x33, 0xa9, 0x03, 0x49, 0x26, 0x64, 0x4e, 0x5f, 0xc0, 0x57, 0xf0, 0xa9, 0x5c, 0xfb, 0x0a, 0x7d,
	0x10, 0x99, 0x99, 0x24, 0xfd, 0x23, 0xf5, 0xae, 0xda, 0xef, 0xcc, 0x77, 0x7e, 0xdf, 0x39, 0x33,
	0x01, 0x40, 0x59, 0xc8, 0xb4, 0xed, 0x24, 0x4a, 0xea, 0xd7, 0xa2, 0x29, 0xca, 0x8a, 0xa9, 0x1f,
	0xa9, 0xae, 0x86, 0xaf, 0x76, 0x52, 0xee, 0x2a, 0x9e, 0xb1, 0x56, 0x64, 0xac, 0x69, 0x24, 0x32,
	0x14, 0xb2, 0x51, 0xd6, 0x1d, 0x2e, 0xfb, 0x53, 0xa3, 0x36, 0xfb, 0x32, 0x43, 0x51, 0x73, 0x85,
	0xac, 0x6e, 0xad, 0x21, 0x3e, 0x10, 0x98, 0xac, 0x65, 0x21, 0xa9, 0x0f, 0x8e, 0x28, 0x02, 0x12,
	0x91, 0x64, 0x9e, 0x3b, 0xa2, 0xa0, 0x21, 0xcc, 0xb6, 0xb2, 0x6e, 0x2b, 0x8e, 0x3c, 0x70, 0x22,
	0x92, 0xcc, 0xf2, 0x51, 0xd3, 0xf7, 0xf0, 0x7c, 0xf8, 0x5f, 0x7c, 0x67, 0x18, 0xdc, 0x44, 0x24,
	0xf1, 0x56, 0x61, 0x6a, 0xc3, 0xd2, 0x21, 0x2c, 0x5d, 0x0f, 0x61, 0xb9, 0x37, 0xfa, 0x1f, 0x90,
	0xbe, 0x05, 0xd8, 0x76, 0x9c, 0xf5, 0xcd, 0x93, 0x27, 0x9b, 0xe7, 0xbd, 0xfb, 0x01, 0x69, 0x04,
	0x5e, 0xc1, 0xd5, 0xb6, 0x13, 0xad, 0xde, 0x32, 0x70, 0xcd, 0xb8, 0xa7, 0x25, 0xba, 0x00, 0x17,
	0x05, 0x56, 0x3c, 0x98, 0x9a, 0x33, 0x2b, 0xe2, 0x47, 0xb8, 0xfd, 0x68, 0x20, 0x7a, 0xd7, 0xc7,
	0xa6, 0xdd, 0xff, 0x83, 0x22, 0xff, 0x41, 0x39, 0xa7, 0xa8, 0x7b, 0x78, 0x71, 0x44, 0x7d, 0xde,
	0xa3, 0x66, 0x25, 0x30, 0xd1, 0x8f, 0x61, 0x20, 0xde, 0x6a, 0x91, 0x9e, 0xbf, 0x51, 0xaa, 0x9d,
	0xb9, 0x71, 0xc4, 0xf7, 0xe0, 0x7f, 0x12, 0x0a, 0x75, 0x45, 0xd9, 0x39, 0x16, 0xe0, 0xb2, 0x12,
	0x79, 0xd7, 0x4f, 0x60, 0x85, 0xae, 0x96, 0xa2, 0x53, 0x68, 0xb2, 0xdd, 0xdc, 0x8a, 0xf8, 0x0b,
	0xdc, 0x8e, 0xdd, 0x7d, 0xf4, 0x1d, 0xb8, 0x1a, 0xac, 0x02, 0x12, 0xdd, 0x5c, 0xcd, 0xb6, 0x16,
	0xb3, 0x90, 0x44, 0x56, 0x0d, 0x50, 0x23, 0x56, 0xbf, 0x09, 0xb8, 0x86, 0x48, 0x37, 0x00, 0xc7,
	0xd5, 0xe8, 0xf2, 0x12, 0x75, 0x71, 0x83, 0x61, 0x74, 0xdd, 0x60, 0x87, 0x8b, 0x5f, 0xfe, 0xfc,
	0x73, 0xf8, 0xe5, 0x78, 0xf1, 0x34, 0x33, 0x03, 0xbc, 0x23, 0x77, 0xf4, 0x1b, 0xcc, 0xc7, 0x15,
	0xe8, 0xeb, 0x4b, 0xc2, 0xf9, 0xdd, 0x84, 0xcb, 0xab, 0xe7, 0x7d, 0x80, 0x6f, 0x02, 0x66, 0xb4,
	0x0f, 0xf8, 0xf0, 0xec, 0xab, 0x6b, 0x3f, 0xa0, 0xa9, 0xf9, 0x79, 0xf3, 0x37, 0x00, 0x00, 0xff,
	0xff, 0xc8, 0xd7, 0xf2, 0xa3, 0x3b, 0x03, 0x00, 0x00,
}
