elasticsearch:
  aws: false
  host: http://localhost:9200

graphql:
  enable_graphiql: true
  enable_mocking: true
  enable_voyager: true

http:
  port: 3000

log:
  level: trace

mysql:
  database: socap
  host: localhost
  password: s3cr3t
  sync: true
  user: graphql