// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CompleteTodoInput struct {
	ID string `json:"id"`
}
type CreateTodoInput struct {
	Description *string `json:"description"`
	Title       string  `json:"title"`
}
type Node interface{}
type PageInfo struct {
	Total *int `json:"total"`
}
type Todo struct {
	ID          string  `json:"id"`
	Complete    bool    `json:"complete"`
	CompletedAt *string `json:"completed_at"`
	CreatedAt   string  `json:"created_at"`
	Description *string `json:"description"`
	Title       string  `json:"title"`
}
type TodosQueryConnection struct {
	Edges    []*TodosQueryEdge `json:"edges"`
	PageInfo *PageInfo         `json:"pageInfo"`
}
type TodosQueryEdge struct {
	Cursor string `json:"cursor"`
	Node   *Todo  `json:"node"`
}
type TodosQueryInput struct {
	After *string `json:"after"`
	First *int    `json:"first"`
	Query *string `json:"query"`
}
